ptrack-new/JavaSource/org/jia/ptrack/domain/Status.java
package org.jia.ptrack.domain;

import java.io.Serializable;

public interface Status extends Serializable {
	public String getId();

	public String getName();

	public Status getApprovalStatus();

	public Status getRejectionStatus();

	public boolean isInitialState();

	public boolean isFinalState();

	public RoleType getRole();

	public StatusCoordinator getCoordinator();
}

ptrack-new/WebContent/WEB-INF/includes/project_artifacts.xhtml
<ui:composition xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html">

<ui:remove>Edit the artifact list.
     Must be included in a panel grid with two columns.
     </ui:remove>

<h:outputLabel for="artifactSelect" value="Completed artifacts:" />
<h:selectManyCheckbox id="artifactSelect" layout="pageDirection"
	styleClass="project-input" value="#{visit.currentProject.artifacts}">
	<f:selectItems value="#{selectItems.artifacts}" />
</h:selectManyCheckbox>
</ui:composition>

ptrack-new/WebContent/WEB-INF/includes/project_info.xhtml
<ui:composition xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html">
	
<ui:remove> Edit and display fields for main project details (approval and rejection).
     Must be included in a panel grid with two columns.
     </ui:remove>

<h:outputText value="Name:" />
<h:outputText value="#{updateProjectBean.project.name}"
	styleClass="project-data" />

<h:outputText value="Type:" />
<h:outputText value="#{updateProjectBean.project.type}"
	styleClass="project-data" />

<h:outputText value="Initiated by:" />
<h:outputText value="#{updateProjectBean.project.initiatedBy}"
	styleClass="project-data" />

<h:outputText value="Requirements contact:" />
<h:outputText value="#{updateProjectBean.project.requirementsContact}"
	styleClass="project-data" />

<h:outputText value="Requirements contact e-mail:" />
<h:outputText value="#{updateProjectBean.project.requirementsContactEmail}"
	styleClass="project-data" />

<h:outputText value="Initial comments:" />
<h:outputText value="#{updateProjectBean.project.initialComments}"
	styleClass="project-data" />
</ui:composition>

ptrack-new/WebContent/WEB-INF/includes/toolbar.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:form id="tf">
	<h:panelGrid columns="4" cellspacing="0" cellpadding="0"
		styleClass="header" width="100%">
		<h:panelGrid id="header" columns="5" cellpadding="4" cellspacing="0"
			border="0">
			<h:outputText value="ProjectTrack:" styleClass="toolbar-header" />
			<h:commandLink action="inbox">
				<h:graphicImage url="/resources/images/inbox.gif"
					styleClass="toolbar-icon" alt="Inbox" />
				<h:outputText value="Inbox" styleClass="toolbar-command" />
			</h:commandLink>
			<h:commandLink action="show_all">
				<h:graphicImage url="/resources/images/show_all.gif"
					styleClass="toolbar-icon" alt="Show all projects" />
				<h:outputText value="Show all" styleClass="toolbar-command" />
			</h:commandLink>
			<h:commandLink action="create">
				<h:graphicImage url="/resources/images/create.gif"
					styleClass="toolbar-icon" alt="Create a new project" />
				<h:outputText value="Create new" styleClass="toolbar-command" />
			</h:commandLink>
			<h:commandLink action="#{loginController.logout}">
				<h:graphicImage url="/resources/images/logout.gif"
					styleClass="toolbar-icon" alt="Logout" />
				<h:outputText value="Logout" styleClass="toolbar-command" />
			</h:commandLink>
		</h:panelGrid>
		<h:outputText value="(#{visit.user.firstName})" styleClass="user-name" />
	</h:panelGrid>
</h:form>
</html>