ptrack-new/JavaSource/org/jia/ptrack/domain/Project.java
package org.jia.ptrack.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.validation.constraints.Future;

import org.jia.ptrack.domain.validation.Email1;

public class Project implements Serializable {

	private static final long serialVersionUID = 9132317118071206063L;

	private String name;
	private String initiatedBy;
	private String requirementsContact;
	private String description;
	private List<Operation> operationHistory;
	private ArtifactType[] artifacts;
	private ProjectType type;
	private String id;
	private Status status;
	private String initialComments;

	@Email1
	private String requirementsContactEmail;

	@Future
	private Date startDate;
	@Future
	private Date dueDate;
	private Long budget;

	public Project() {
		operationHistory = new ArrayList<Operation>();
		artifacts = new ArtifactType[] {};
	}

	public Project(Status initialStatus) {
		this();
		setInitialStatus(initialStatus);
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}

	public void setInitiatedBy(String initiatedBy) {
		this.initiatedBy = initiatedBy;
	}

	public String getInitiatedBy() {
		return initiatedBy;
	}

	public void setRequirementsContact(String requirementsContact) {
		this.requirementsContact = requirementsContact;
	}

	public String getRequirementsContact() {
		return requirementsContact;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDescription() {
		return description;
	}

	public List<Operation> getHistory() {
		return Collections.unmodifiableList(operationHistory);
	}

	public void setArtifacts(ArtifactType[] artifacts) {
		this.artifacts = artifacts;
	}

	public ArtifactType[] getArtifacts() {
		return artifacts;
	}

	public void setType(ProjectType type) {
		this.type = type;
	}

	public ProjectType getType() {
		return type;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getId() {
		return id;
	}

	public Status getStatus() {
		return status;
	}

	public synchronized boolean changeStatus(boolean approve, User user,
			String comments) {
		return changeStatus(new Date(), approve, user, comments);
	}

	public synchronized boolean changeStatus(Date date, boolean approve,
			User user, String comments) {
		if (status == null) {
			throw new NullPointerException(
					"The initialStatus property must be "
							+ "set before the status can be changed.");
		}

		if (!status.getCoordinator().isValidStateChange(status, approve)) {
			return false;
		}

		final Status fromStatus = status;
		Status toStatus = null;

		if (approve) {
			toStatus = status.getApprovalStatus();
		} else {
			toStatus = status.getRejectionStatus();
		}

		final Operation newAction = new Operation(date, user, fromStatus,
				toStatus, comments);
		operationHistory.add(newAction);
		status = toStatus;
		return true;
	}

	public void setInitialStatus(Status initialStatus) {
		if (status == null) {
			status = initialStatus;
		}
	}

	public Map<String, String> getIdMap() {
		final Map<String, String> idMap = new HashMap<String, String>();
		idMap.put(name, id);
		return idMap;
	}

	public void setInitialComments(String initialComments) {
		this.initialComments = initialComments;
	}

	public String getInitialComments() {
		return initialComments;
	}

	@Override
	public String toString() {
		return name;
	}

	public String getRequirementsContactEmail() {
		return requirementsContactEmail;
	}

	public void setRequirementsContactEmail(String requirementsContactEmail) {
		this.requirementsContactEmail = requirementsContactEmail;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getDueDate() {
		return dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	public Long getBudget() {
		return budget;
	}

	public void setBudget(Long budget) {
		this.budget = budget;
	}
}

ptrack-new/JavaSource/org/jia/ptrack/domain/Status.java
package org.jia.ptrack.domain;

import java.io.Serializable;

public interface Status extends Serializable {
	public String getId();

	public String getName();

	public Status getApprovalStatus();

	public Status getRejectionStatus();

	public boolean isInitialState();

	public boolean isFinalState();

	public RoleType getRole();

	public StatusCoordinator getCoordinator();
}

ptrack-new/JavaSource/org/jia/ptrack/web/ShowHistoryBean.java
/**
   JavaServer Faces in Action example code, Copyright (C) 2004 Kito D. Mann.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

 **/

package org.jia.ptrack.web;

import java.util.List;

import javax.faces.component.UIData;
import javax.faces.event.ActionEvent;
import javax.inject.Named;

import org.jia.ptrack.domain.Operation;

@Named
public class ShowHistoryBean extends BaseController {
	private static final long serialVersionUID = -3095649130278282549L;

	private int rowsPerPage = 5;
	private UIData historyDataTable;

	public ShowHistoryBean() {
	}

	public UIData getHistoryDataTable() {
		return historyDataTable;
	}

	public void setHistoryDataTable(UIData historyDataTable) {
		this.historyDataTable = historyDataTable;
	}

	public int getRowsPerPage() {
		return rowsPerPage;
	}

	public void setRowsPerPage(int rowsPerPage) {
		this.rowsPerPage = rowsPerPage;
	}

	public List<Operation> getCurrentProjectHistory() {
		return getVisit().getCurrentProject().getHistory();
	}

	public boolean getShowNext() {
		return historyDataTable.getFirst() + rowsPerPage < getCurrentProjectHistory()
				.size();
	}

	public boolean getShowPrevious() {
		return historyDataTable.getFirst() - rowsPerPage >= 0;
	}

	public void next(ActionEvent actionEvent) {
		final int newFirst = historyDataTable.getFirst() + rowsPerPage;
		if (newFirst < getCurrentProjectHistory().size()) {
			historyDataTable.setFirst(newFirst);
		}
	}

	public void previous(ActionEvent actionEvent) {
		final int newFirst = historyDataTable.getFirst() - rowsPerPage;
		if (newFirst >= 0) {
			historyDataTable.setFirst(newFirst);
		}
	}

}

ptrack-new/WebContent/views/details.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ptc="http://xmlns.jcp.org/jsf/composite/ptrack-components"
	template="/templates/standard.xhtml">

	<ui:define name="titleText">ProjectTrack - Details</ui:define>
	<ui:define name="content">
		<f:metadata>
			<f:viewParam name="projectId" value="#{projectDetailsController.projectId}"
				required="true">
				<f:validateLength minimum="1" maximum="5" />
			</f:viewParam>
			<f:viewParam name="fromInbox" value="#{projectDetailsController.fromInbox}" />
			<f:viewAction 
				actionListener="#{projectDetailsController.loadProject()}" />
		</f:metadata>
		<h:form id="f" styleClass="project-background">
			<ptc:projectInfo title="Projet details"
				value="#{projectDetailsController.project}" showComments="false" />

			<h:dataTable id="histDtb" cellpadding="5"
				styleClass="table-background" columnClasses="details-column"
				value="#{projectDetailsController.project.history}" var="operation"
				first="#{projectDetailsController.firstRow}"
				rows="#{projectDetailsController.rowsPerPage}">

				<f:facet name="header">
					<h:outputText value="History" styleClass="table-header" />
				</f:facet>

				<h:column>
					<h:panelGrid columns="1" width="100%" styleClass="table-even-row">

						<h:panelGrid columns="3" cellpadding="7"
							styleClass="table-even-row">
							<h:outputText value="#{operation.timestamp}">
								<f:convertDateTime dateStyle="full" timeStyle="short" />
							</h:outputText>
							<h:outputText
								value="#{operation.fromStatus} -> #{operation.toStatus}" />
							<h:outputText value="(#{operation.user.role.description})" />
						</h:panelGrid>

						<h:panelGrid columns="1" cellpadding="3"
							styleClass="table-odd-row" width="100%">
							<h:outputText value="Comments:" />
							<h:outputText value="#{operation.comments}"
								styleClass="project-data" />
						</h:panelGrid>
					</h:panelGrid>
				</h:column>

				<f:facet name="footer">
					<h:panelGroup>
						<h:commandLink id="previous"
							actionListener="#{projectDetailsController.previous}"
							rendered="#{projectDetailsController.showPrevious}"
							style="padding-right: 5px;" value="Previous">
							<f:ajax render=":f:histDtb" />
						</h:commandLink>
						<h:commandLink id="next"
							actionListener="#{projectDetailsController.next}"
							rendered="#{projectDetailsController.showNext}" value="Next">
							<f:ajax render=":f:histDtb" />
						</h:commandLink>
					</h:panelGroup>
				</f:facet>
			</h:dataTable>
			<h:commandButton id="ok" value="OK" action="success"
				immediate="true" style="margin-top: 5px">
				<f:ajax />
			</h:commandButton>
		</h:form>
	</ui:define>
</ui:composition>

ptrack-new/WebContent/views/error.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	template="/templates/master.xhtml">

	<ui:define name="title">ProjectTrack - Error</ui:define>
	<ui:define name="body">
			<h:messages globalOnly="true" styleClass="errors"/>
	</ui:define>	
	
</ui:composition>  

ptrack-new/WebContent/views/show_all.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:custom="urn:org.jia.ptrack"
	template="/templates/standard.xhtml">

	<ui:define name="titleText">ProjectTrack - Show all projects</ui:define>
	<ui:define name="content">
		<h:form id="form">
			<h:panelGrid headerClass="page-header" styleClass="table-background"
				columns="1" cellpadding="5">
				<f:facet name="header">
					<h:outputText value="Show all projects" />
				</f:facet>
				<h:messages globalOnly="true" styleClass="errors" />
				<h:dataTable styleClass="table-background"
					rowClasses="table-odd-row,table-even-row" cellpadding="3"
					value="#{selectProjectController.getProjects(true)}" var="project">
					<h:column>
						<f:facet name="header">
							<h:outputText value="Project name" />
						</f:facet>
						<h:outputText value="#{project.name}" />
					</h:column>
					<h:column>
						<f:facet name="header">
							<h:outputText value="Type" />
						</f:facet>
						<h:outputText value="#{project.type}">
							<custom:enumConverter />
						</h:outputText>
					</h:column>
					<h:column>
						<f:facet name="header">
							<h:outputText value="Status" />
						</f:facet>
						<h:outputText value="#{project.status}" />
					</h:column>
					<h:column>
						<h:link id="details" outcome="details" value="Details">
							<f:param name="projectId" value="#{project.id}" />
							<f:param name="fromInbox" value="false" />
						</h:link>
					</h:column>
				</h:dataTable>
			</h:panelGrid>
		</h:form>
	</ui:define>
</ui:composition>